### PR TITLE
Handle "max serialization size" of the storage backend

### LINKED ISSUE #30: Handle "max serialization size" of the storage backend
Yes, so a single item cannot be larger than a page/sector. This can be checked though.
The maximum size that s-s can fit is a page size minus two word sizes and minus [item overhead](https://docs.rs/sequential-storage/4.0.1/sequential_storage/fn.item_overhead_size.html).

So maybe it's worth checking that. Then the distinction can be made between 'serialization failed' and 'item too big'.

_Originally posted by @diondokter in https://github.com/tweedegolf/cfg-noodle/pull/28#discussion_r2142077762_

### PR DESCRIPTION
**Pull request by JuliDi**
Fixes #30

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -167,6 +172,9 @@ pub trait NdlDataStorage {
     /// Cancellation MUST NOT lead to data loss, other than the element currently
     /// being written.
     async fn push(&mut self, data: &Elem<'_>) -> Result<(), Self::Error>;
+    
+    /// Return the maximum size of an `Elem` that may be stored in the list in bytes.
```
Comment (jamesmunns) [inline src/lib.rs:176]:
```suggestion
    /// Return the maximum size of an `Elem` that may be stored in the list in bytes.
    ///
    /// This includes a one byte element header, the CBOR-serialized key, and the
    /// CBOR-serialized value.
```

File: src/storage_list.rs [hunk 2]
```diff
@@ -195,15 +195,19 @@ impl<R: ScopedRawMutex> StorageList<R> {
...
+    /// - `buf`: a scratch-buffer of length `S::MAX_ELEM_SIZE`.
     ///
     pub async fn process_reads<S: NdlDataStorage>(
         &'static self,
         storage: &mut S,
         buf: &mut [u8],
     ) -> Result<(), LoadStoreError<S::Error>> {
         info!("Start process_reads");
+
+        if buf.len() != S::MAX_ELEM_SIZE {
```
Comment (jamesmunns) [inline src/storage_list.rs:207]: I'm actually not sure if we want to enforce this as such. If we are using a driver that has 4K sectors, but we know we only ever put <128 byte items into storage, we don't necessarily want to require that users always provide that.

It might be worth a `warn!` in this case, something like "mismatch in size of buffer provided ({bufsz}), vs storage's MAX_ELEM_SIZE ({stosz}). Maximum item size will be limited to {min(bufsz, stosz)}."

File: src/storage_list.rs [hunk 3]
```diff
@@ -250,16 +254,18 @@ impl<R: ScopedRawMutex> StorageList<R> {
...
-    ///   sufficient.
+    /// * `buf`: a scratch-buffer of length `S::MAX_ELEM_SIZE`.
     pub async fn process_writes<S: NdlDataStorage>(
         &'static self,
         storage: &mut S,
         buf: &mut [u8],
     ) -> Result<(), LoadStoreError<S::Error>> {
         debug!("Start process_writes");
 
+        if buf.len() != S::MAX_ELEM_SIZE {
```
Comment (jamesmunns) [inline src/storage_list.rs:265]: Same note as above.

File: src/storage_list.rs (hunk 2 above)
Comment (JuliDi) [reply src/storage_list.rs:207]: Agreed, forcing the user to provide such a huge buffer is too restrictive. I will add a warning instead.
